customization:
  distribution_code_name: Weasel
  distribution_version: 0.17.4
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Feb 22 22:26:37 2026"
  rime_version: 1.13.1
patch:
  "style/color_scheme": poetry_ocean
  "style/color_scheme_dark": dark_ocean